decproj2:
  outputs:
    dev:
      account: xkofovp-cpb51387
      database: dw1
      password: '{{ env_var("SNOWFLAKE_PASSWORD") }}'
      role: accountadmin
      schema: raw
      threads: 10
      type: snowflake
      user: '{{ env_var("SNOWFLAKE_USERNAME") }}'
      warehouse: xsmall_wh
  target: dev
